### PR TITLE
Add Pinnacles Campground

### PR DESCRIPTION
**Pull request by wllmtrng**

### CODE REVIEW

**Comment by wllmtrng** [comment]
Mind if you added another park?

**Comment by tiwatson** [comment]
Thanks... I just deployed it. Should be available for use.

Not sure why but a few national park campgrounds got left out.

**Comment by wllmtrng** [comment]
thanks! this is an awesome service

**Comment by wllmtrng** [comment]
Still not seeing it available on http://reserve.wanderinglabs.com/. Maybe servers need to be restarted?

**Comment by tiwatson** [comment]
Forgot a git pull before I deployed. Not used to deploying from local master. 

It is there now.

**Pull request merged**
